### PR TITLE
Fix bug with command lengths over 127

### PR DESCRIPTION
**Pull request by kheimerl**
Small bug fix to CLI parsing. Orphaned range patch.

### CODE REVIEW

**Comment by kheimerl** [comment]
Hi @Will-W  , we're merging old orphaned openbts patches. Do you mind if we use this?

Thanks!

**Comment by Will-W** [comment]
No, please do - that was the intention!

Will

**Comment by kheimerl** [comment]
ptal

**Comment by shaddi** [comment]
lgtm

**Pull request merged**
