### PR TITLE
Updating default value of SMS port to point to freeswitch

### PR DESCRIPTION
**Pull request by kkroo**
This is a one-liner PR to update the SMS Proxy to point to FS by default

### CODE REVIEW

**Comment by kheimerl** [comment]
You sure we use this file to generate the database?

**Comment by kkroo** [comment]
After installing the openbts deb, (https://github.com/endaga/openbts/blob/master/debian/postinst#L31)[this postinst script] gets called which builds the database off of ``/etc/OpenBTS/OpenBTS.example.sql``

This file is what gets copied over in the makefile.

**Comment by kheimerl** [comment]
That sounds right. I know that OpenBTS will autofill the DB if fields are
missing, so that's something to watch for. Probably fine though.

**Comment by kkroo** [comment]
You are right, we're not really setting the DB fields anywhere which is the real problem. We've got configs coming via checkin updates. Since we're probably going to have a growing list of default config values, it is probably better to get an initialization list on the client

**Comment by kkroo** [comment]
I'm also thinking about maintaining the ability to merge with range's openbts without causing too many conflicts. Editing here is probably the safest thing to do, but merging is going to be a pain in the ass every time there is an update..

**Comment by shaddi** [comment]
We already set Endaga-specific config variables in an initialization script in the client; we could extend that to support OpenBTS configs as well and do this stuff there. The closer we can keep to mainline OpenBTS the better (due to ease of merging/pushing bugfixes back) imo.

**Comment by kkroo** [comment]
Agreed. I found the postinit script you are referring to under client. Closing this PR

**Pull request closed without merging**
