### PR TITLE
Fix gprs slots

### PR DESCRIPTION
**Pull request by kheimerl**
Omar wants a pull request

### CODE REVIEW

**Comment by kkroo** [comment]
gprs doesnt start:

`Jul 21 00:02:49 endaga-demo2 openbts: ERR 1132:1132 2015-07-21T00:02:49.8 MAC.cpp:747:macPacchAddAdjCh:   00:02:49.8,605013:logic error in leftover PACCH calculation`

**Comment by kheimerl** [comment]
This may be a bad channel selection, it looks like there's a specific alignment required.

**Comment by kheimerl** [comment]
any way to repro this?

**Comment by kkroo** [comment]
just `gprs start`

**Comment by kkroo** [comment]
can't repro anymore...

**Comment by kheimerl** [comment]
I feel like there are a lot of startup race conditions here and our fix optimized a portion of the code to caused them to go off sometimes.

**Comment by kheimerl** [comment]
omar has blessed, so I am merging

**Pull request merged**
