### PR TITLE
bumps changelog

### PR DESCRIPTION
**Pull request by yosemitebandit**
hm I was on master and did a did a `git reset --hard ed436d4073bf42f8f5221ed3d4bcdb5fb6c89a64` but I'm not sure it worked properly?

### CODE REVIEW

**Comment by yosemitebandit** [comment]
commit history seems to be where we want it..PTAL

**Comment by shaddi** [comment]
lgtm :rocket:

**Comment by yosemitebandit** [comment]
not sure if I should merge this one -- won't it reset master's history back to ed43d6?  I can just do a release from this branch but not merge..

**Comment by shaddi** [comment]
Ah right. Merge it into the `release-5.0.1` branch... though I guess it's already there. :-) So let's just close this out.

**Pull request closed without merging**
